#!/usr/bin/env python
"docstring: this is the script for get all snapshots' size and size warning email to admin"

import boto.ec2
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
import sys
from os.path import basename

sys.stdout=open("Output_Log.txt","w")
connection = boto.ec2.connect_to_region(
        "cn-north-1",
        aws_access_key_id='YOUR AWS ACCESS KEY ID HERE',
        aws_secret_access_key='YOUR AWS SECRET KEY HERE')

snapshots = connection.get_all_snapshots(owner='self')
size_total = 0
for s in snapshots:
    size_total += s.volume_size
    print('The size of %s is %dGB.' %(s.id, s.volume_size))

print("#Output file# Total size of all snapshots is %dGB" % size_total)

sys.stdout.close()


if size_total > 5000:

    msg = MIMEMultipart()
    # Create a text/plain message
    body = 'Warning! Total snapshots size is %dGB now, and it exceeds allowed value' % (size_total)
    msg.attach(MIMEText(body))

    filename = 'Output_Log.txt'
    attachment = open(filename, 'rb')
    part = MIMEApplication(attachment.read(), Name=basename(filename))
    part['Content-Disposition'] = 'attachment; filename="%s"' % basename(filename)
    msg.attach(part)


    fromaddr = "YOUR EMAIL ADDRESS HERE"
    toaddr = "YOUR ADMINISTRATOR EMAIL ADDRESS HERE"
    msg['From'] = fromaddr
    msg['To'] = toaddr
    msg['Subject'] = "Warning! Total snapshots size exceeds allowed value"


    s = smtplib.SMTP_SSL('smtp.qq.com', 465)
    s.login('YOUR EMAIL ADDRESS HERE', 'YOUR EMAIL PASSWORD OR APP CODE HERE')
    s.sendmail(fromaddr, toaddr, msg.as_string())
    s.quit()

